/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




public class Coach_CreatePlayer extends javax.swing.JFrame {
    
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form Home
     */
    public Coach_CreatePlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        physical = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        createPlayer = new javax.swing.JLabel();
        player_name = new javax.swing.JTextField();
        defense = new javax.swing.JTextField();
        dribble = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        shoot = new javax.swing.JTextField();
        pace = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        physical.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        physical.setForeground(new java.awt.Color(0, 153, 0));
        physical.setBorder(null);
        getContentPane().add(physical, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 180, 20));

        back.setText(" ");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 90, 30));

        createPlayer.setText(" ");
        getContentPane().add(createPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 100, 20));

        player_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        player_name.setForeground(new java.awt.Color(0, 153, 0));
        player_name.setBorder(null);
        getContentPane().add(player_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 180, 20));

        defense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        defense.setForeground(new java.awt.Color(0, 153, 0));
        defense.setBorder(null);
        getContentPane().add(defense, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 180, 20));

        dribble.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dribble.setForeground(new java.awt.Color(0, 153, 0));
        dribble.setBorder(null);
        getContentPane().add(dribble, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 180, 20));

        pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 153, 0));
        pass.setBorder(null);
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 180, 20));

        shoot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shoot.setForeground(new java.awt.Color(0, 153, 0));
        shoot.setBorder(null);
        getContentPane().add(shoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 180, 20));

        pace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pace.setForeground(new java.awt.Color(0, 153, 0));
        pace.setBorder(null);
        getContentPane().add(pace, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 180, 20));

        position.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        position.setForeground(new java.awt.Color(0, 153, 0));
        position.setBorder(null);
        getContentPane().add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 180, 20));

        page.setIcon(new javax.swing.ImageIcon("C:\\Users\\giann\\Downloads\\Mockups-FM\\Mockups\\FM-CA-Create Player.png")); // NOI18N
        page.setText(" ");
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Coach_Squad a = new Coach_Squad();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel createPlayer;
    private javax.swing.JTextField defense;
    private javax.swing.JTextField dribble;
    private javax.swing.JTextField pace;
    private javax.swing.JLabel page;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField physical;
    private javax.swing.JTextField player_name;
    private javax.swing.JTextField position;
    private javax.swing.JTextField shoot;
    // End of variables declaration//GEN-END:variables
}
