/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Coach_InsertData extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Coach_InsertData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jComboBox_Against = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        jComboBox_Possession = new javax.swing.JComboBox<>();
        jComboBox_Passes = new javax.swing.JComboBox<>();
        jComboBox_Attempts = new javax.swing.JComboBox<>();
        jComboBox_Fouls = new javax.swing.JComboBox<>();
        jComboBox_Offside = new javax.swing.JComboBox<>();
        jComboBox_OnTarget = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        page.setIcon(new javax.swing.ImageIcon("C:\\Users\\giann\\Downloads\\Mockups-FM\\Mockups\\FM-CA-Insert Match Data.png")); // NOI18N
        page.setText(" ");
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        back.setText(" ");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 20, 90, 30));

        jComboBox_Against.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AEK", "Aris", "Olympiakos", "Panathinaikos", "PAOK" }));
        jComboBox_Against.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AgainstActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Against, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 130, -1));

        save.setText("jButton1");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 100, 20));

        jComboBox_Possession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%", " " }));
        jComboBox_Possession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PossessionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Possession, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 130, 20));

        jComboBox_Passes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", " " }));
        jComboBox_Passes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PassesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Passes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 130, 20));

        jComboBox_Attempts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jComboBox_Attempts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AttemptsActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Attempts, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 130, 20));

        jComboBox_Fouls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jComboBox_Fouls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FoulsActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Fouls, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 130, 20));

        jComboBox_Offside.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jComboBox_Offside.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_OffsideActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Offside, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 130, 20));

        jComboBox_OnTarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jComboBox_OnTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_OnTargetActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_OnTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 130, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Coach a = new Coach();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
    
    }//GEN-LAST:event_saveMouseClicked

    private void jComboBox_AgainstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AgainstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_AgainstActionPerformed

    private void jComboBox_PossessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PossessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_PossessionActionPerformed

    private void jComboBox_PassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PassesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_PassesActionPerformed

    private void jComboBox_AttemptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AttemptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_AttemptsActionPerformed

    private void jComboBox_FoulsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FoulsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_FoulsActionPerformed

    private void jComboBox_OffsideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_OffsideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_OffsideActionPerformed

    private void jComboBox_OnTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_OnTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_OnTargetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JComboBox<String> jComboBox_Against;
    private javax.swing.JComboBox<String> jComboBox_Attempts;
    private javax.swing.JComboBox<String> jComboBox_Fouls;
    private javax.swing.JComboBox<String> jComboBox_Offside;
    private javax.swing.JComboBox<String> jComboBox_OnTarget;
    private javax.swing.JComboBox<String> jComboBox_Passes;
    private javax.swing.JComboBox<String> jComboBox_Possession;
    private javax.swing.JLabel page;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
