/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Physiotherapist_StengthEx extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Physiotherapist_StengthEx() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        page = new javax.swing.JLabel();
        jComboBox_Plan = new javax.swing.JComboBox<>();
        create = new javax.swing.JButton();
        import_video = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText(" ");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 90, 30));

        page.setIcon(new javax.swing.ImageIcon("C:\\Users\\giann\\Downloads\\Mockups-FM\\Mockups\\FM-Phys-Strength.png")); // NOI18N
        page.setText(" ");
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        jComboBox_Plan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Str. Exercise 1", "Str. Exercise 2", "Str. Exercise 3", "Str. Exercise 4" }));
        jComboBox_Plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PlanActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Plan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 220, 30));

        create.setText("jButton1");
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 120, 20));

        import_video.setText("jButton1");
        getContentPane().add(import_video, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 120, 20));

        edit.setText("jButton1");
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 120, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Physiotherapist a = new Physiotherapist();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void jComboBox_PlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_PlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton create;
    private javax.swing.JButton edit;
    private javax.swing.JButton import_video;
    private javax.swing.JComboBox<String> jComboBox_Plan;
    private javax.swing.JLabel page;
    // End of variables declaration//GEN-END:variables
}
