/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Physiotherapist extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Physiotherapist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        strengthEx = new javax.swing.JLabel();
        injuryEx = new javax.swing.JLabel();
        injuryDashboard = new javax.swing.JLabel();
        trackProgress = new javax.swing.JLabel();
        videoLibray = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        strengthEx.setText(" ");
        strengthEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                strengthExMouseClicked(evt);
            }
        });
        getContentPane().add(strengthEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 250, 20));

        injuryEx.setText(" ");
        injuryEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                injuryExMouseClicked(evt);
            }
        });
        getContentPane().add(injuryEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 310, 30));

        injuryDashboard.setText(" ");
        getContentPane().add(injuryDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 220, 30));

        trackProgress.setText(" ");
        getContentPane().add(trackProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 180, 30));

        videoLibray.setText(" ");
        videoLibray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videoLibrayMouseClicked(evt);
            }
        });
        getContentPane().add(videoLibray, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 170, 30));

        logout.setText(" ");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 20, 110, 30));

        page.setIcon(new javax.swing.ImageIcon("C:\\Users\\giann\\Downloads\\Mockups-FM\\Mockups\\FMPhysiotherapists.png")); // NOI18N
        page.setText(" ");
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void strengthExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strengthExMouseClicked
        Physiotherapist_StengthEx a = new Physiotherapist_StengthEx();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_strengthExMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Home a = new Home();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void injuryExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_injuryExMouseClicked
        Physiotherapist_InjuryEx a = new Physiotherapist_InjuryEx();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_injuryExMouseClicked

    private void videoLibrayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoLibrayMouseClicked
        Physiotherapist_VideoLibrary a = new Physiotherapist_VideoLibrary();
        a.setVisible(true);
        this.dispose();    }//GEN-LAST:event_videoLibrayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel injuryDashboard;
    private javax.swing.JLabel injuryEx;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel page;
    private javax.swing.JLabel strengthEx;
    private javax.swing.JLabel trackProgress;
    private javax.swing.JLabel videoLibray;
    // End of variables declaration//GEN-END:variables
}
