
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Player_MyCalendar extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Player_MyCalendar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        training = new javax.swing.JLabel();
        nutrition = new javax.swing.JLabel();
        physiotherapy = new javax.swing.JLabel();
        recommendation = new javax.swing.JLabel();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText(" ");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 90, 30));

        training.setText(" ");
        training.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainingMouseClicked(evt);
            }
        });
        getContentPane().add(training, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 30, 10));

        nutrition.setText(" ");
        nutrition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nutritionMouseClicked(evt);
            }
        });
        getContentPane().add(nutrition, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 30, 10));

        physiotherapy.setText(" ");
        physiotherapy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                physiotherapyMouseClicked(evt);
            }
        });
        getContentPane().add(physiotherapy, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 50, 10));

        recommendation.setText(" ");
        recommendation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recommendationMouseClicked(evt);
            }
        });
        getContentPane().add(recommendation, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 50, 20));

        page.setIcon(new javax.swing.ImageIcon("C:\\Users\\giann\\Downloads\\Mockups-FM\\Mockups\\FM-Pl-MyCalendar.png")); // NOI18N
        page.setText(" ");
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Player a = new Player();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void trainingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainingMouseClicked
        Player_MyCalendar_TrainingPrograms a = new Player_MyCalendar_TrainingPrograms();
        a. setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trainingMouseClicked

    private void nutritionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nutritionMouseClicked
        Player_MyCalendar_Nutrition a = new Player_MyCalendar_Nutrition();
        a. setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nutritionMouseClicked

    private void physiotherapyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_physiotherapyMouseClicked
        Player_MyCalendar_PhysiotherapyEx a = new Player_MyCalendar_PhysiotherapyEx();
        a. setVisible(true);
        this.dispose();
    }//GEN-LAST:event_physiotherapyMouseClicked

    private void recommendationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recommendationMouseClicked
        JOptionPane.showMessageDialog(this,"You do not have any recommendation!","Information",JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_recommendationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel nutrition;
    private javax.swing.JLabel page;
    private javax.swing.JLabel physiotherapy;
    private javax.swing.JLabel recommendation;
    private javax.swing.JLabel training;
    // End of variables declaration//GEN-END:variables
}
